# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target '几何天气' do
pod ‘pop’
pod ‘AFNetworking’
end

target '几何天气Tests' do

end

target '几何天气UITests' do

end

